### ISSUE TITLE
Build failed linux with scon.

### ISSUE THREAD

**Issue by rdtor** [zzkt/fluxus#3]
/bin/ld: /usr/local/lib/racket/libracket3m.a(char.o): relocation R_X86_64_32 against undefined symbol `scheme_false' can not be used when making a PIE object; recompile with -fPIC
/bin/ld: /usr/local/lib/racket/libracket3m.a(compenv.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/bin/ld: /usr/local/lib/racket/libracket3m.a(compile.o): relocation R_X86_64_32S against undefined symbol `scheme_null' can not be used when making a PIE object; recompile with -fPIC
/bin/ld: /usr/local/lib/racket/libracket3m.a(dynext.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/bin/ld: /usr/local/lib/racket/libracket3m.a(marshal.o): relocation R_X86_64_32 against undefined symbol `scheme_null' can not be used when making a PIE object; recompile with -fPIC
/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
scons: *** [fluxus] Error 1

**Comment by zzkt** [comment]
you might want to have a look at the slightly less dusty version @nebogeo has at https://github.com/nebogeo/fluxus
